spring:
  datasource:
    username: root
    password: root
    url: jdbc:mysql://192.168.56.9:3306/gulimall_pms?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  application:
    name: gulimall-product
  jackson:
    date-format: yyyy-MM-dd HH:hh:ss
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html
  redis:
    host: 192.168.56.9
    port: 6379
mybatis-plus:
  mapper-location: classpath:/mapper/**/*.xml
  global-config:
    db-config:
      id-type: auto  # id主键自增
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)
server:
  port: 9094
logging:
  level:
    com.atguigu.gulimall: debug

