spring:
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  application:
    name: gulimall-auth-server
  thymeleaf:
    cache: false
  redis:
    host: 192.168.56.9
    port: 6379
  session:
    store-type: redis
server:
  port: 9095
  servlet:
    session:
      timeout: 30m
logging:
  level:
    com.atguigu.gulimall: debug