spring:
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  application:
    name: gulimall-auth-server
  thymeleaf:
    cache: false
server:
  port: 9095
logging:
  level:
    com.atguigu.gulimall: debug