spring:
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.56.9:8848
    alicloud:
      access-key: xxx
      secret-key: xxxx
      oss:
        endpoint: xxx
        bucket: xxx
      sms:
        host: https://xxx.com
        path: /fsms132
        skin: 1
        sign: 1
        appcode: xxx
  application:
    name: gulimall-third-party

server:
  port: 9096

