spring:
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.56.9:8848
  application:
    name: gulimall-cart
  redis:
    host: 192.168.56.9
    port: 6379
server:
  port: 9102
logging:
  level:
    com.atguigu.gulimall: debug
#线程池属性的配置
gulimall:
  thread:
    core: 20
    max-size: 200
    keep-alive-time: 10